# -*- coding: utf-8 -*-
"""10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6VjYyzMHHKVYzSwFJwMDKae0NbYFrJ1
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Concrete Compressive Strength.csv')

df.shape

df.info()

df.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

x = df.drop(columns=['Concrete compressive strength'])
y = df['Concrete compressive strength']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 42)

lr = LinearRegression()
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
r2_score = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print('Mean Absolute Error:', mae)
print('R2 Score:', r2_score)
print('Mean Squared Error:', mse)

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred, color='blue', alpha=0.7, edgecolor='black')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color='red', linewidth=2)
plt.xlabel("Actual Compressive Strength (MPa)")
plt.ylabel("Predicted Compressive Strength (MPa)")
plt.title("Actual vs Predicted Compressive Strength (Linear Regression)")
plt.grid(True)
plt.show()