# -*- coding: utf-8 -*-
"""4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkkbNjmpymt1Skk8ESH4KPg-nhFgNRku
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage

df = pd.read_csv('/content/Clustering_Mall_Customers.csv')

df.shape

df.columns

le = LabelEncoder()
df['Genre'] = le.fit_transform(df['Genre'])

df.head()

x = df[['Annual Income (k$)', 'Spending Score (1-100)']]

sc = StandardScaler()
x_scale = sc.fit_transform(x)

WCSS = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state =42)
  kmeans.fit(x_scale)
  WCSS.append(kmeans.inertia_)

plt.plot(range(1,11), WCSS, color='red')
plt.xlabel('Clusters')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state =42)
y_pred = kmeans.fit_predict(x_scale)

pca = PCA(n_components = 2)
x_pca = pca.fit_transform(x_scale)

plt.scatter(x_pca[y_pred==0,0], x_pca[y_pred==0,1], color='red', label='Cluster 1')
plt.scatter(x_pca[y_pred==1,0], x_pca[y_pred==1,1], color='green', label='Cluster 2')
plt.scatter(x_pca[y_pred==2,0], x_pca[y_pred==2,1], color='blue', label='Cluster 3')
plt.scatter(x_pca[y_pred==3,0], x_pca[y_pred==3,1], color='purple', label='Cluster 4')
plt.scatter(x_pca[y_pred==4,0], x_pca[y_pred==4,1], color='orange', label='Cluster 5')

plt.title('Mall Customers - K-Means Clusters')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.show()

hc = AgglomerativeClustering(n_clusters=5, linkage='ward')
YpredHC = hc.fit_predict(x_scale)

plt.scatter(x_pca[YpredHC==0,0], x_pca[YpredHC==0,1], color='red', label='Cluster 1')
plt.scatter(x_pca[YpredHC==1,0], x_pca[YpredHC==1,1], color='green', label='Cluster 2')
plt.scatter(x_pca[YpredHC==2,0], x_pca[YpredHC==2,1], color='blue', label='Cluster 3')
plt.scatter(x_pca[YpredHC==3,0], x_pca[YpredHC==3,1], color='purple', label='Cluster 4')
plt.scatter(x_pca[YpredHC==4,0], x_pca[YpredHC==4,1], color='orange', label='Cluster 5')
plt.title('Mall Customers - Hierarchical Clusters')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.show()

sil_kmeans = silhouette_score(x_scale, y_pred)
sil_hier = silhouette_score(x_scale, YpredHC)

print(f"\nSilhouette Score (K-Means): {sil_kmeans}")
print(f"Silhouette Score (Hierarchical): {sil_hier}")